### PR TITLE
chore: add Github action to build provider

### PR DESCRIPTION
**Pull request by tommyknows**
We want to get rid of the provider-build step in CSE, building the providers in their own repos makes more sense.

This Github Action creates a release for every commit that is named `v0.0.0-<commit sha>` and attaches a linux/amd64 and darwin/arm64 binary to it.

This same file has run in the azure-provider already: https://github.com/LuminalHQ/terraform-provider-azurerm/commits/snyk
and created [this release](https://github.com/LuminalHQ/terraform-provider-azurerm/releases/tag/v0.0.0-0f500489afe37f8ee990d209f6616cf52ac8d76e).

### CODE REVIEW

**Comment by tommyknows** [comment]
Note: I'm going to do the exact same thing for the google-provider as well, but given that it should simply be a copy-pasta job I'll push directly to the `snyk` branch (if there's no objection)

**Comment by craigfurman** [comment]
Why do we remove every other action? Are those upstream artifacts?

**Comment by tommyknows** [comment]
Yes, previously in this repo Actions were disabled, and now I obviously had to enable them. With that I saw that many artifacts tried to run, which we probably don't want :) 

These artifacts come from upstream, yes (so from the "original" provider) 
Edit: i don't actually know, but I'm assuming they're from upstream 😅

**Review by craigfurman — APPROVED** [review]
🚀

**Pull request merged**
